<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "gh_onetimesession"
 *
 * Auto generated by Extension Builder 2014-05-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Onetime Session',
	'description' => 'Provides a user session with a limited feature set but without the need of fe_users.',
	'category' => 'plugin',
	'author' => 'Gebrüderheitz',
	'author_email' => 'support@gebruederheitz.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
			'powermail' => '2.0.0 - 2.0.999',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);